#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "You must be root in order to install ShuttleMessages."
  exit
fi

apt install python3-pymongo postfix mailutils

mkdir /opt/shuttlemessages
mkdir /opt/shuttlemessages/reports

cp ./ShuttleMessages/shuttlemessages.py /opt/shuttlemessages/shuttlemessages.py
cp ./ShuttleMessages/shuttlemessagestab /opt/shuttlemessages/shuttlemessagestab

crontab /opt/shuttlemessages/shuttlemessagestab
python3 /opt/shuttlemessages/shuttlemessages.py --add-mails
python3 /opt/shuttlemessages/shuttlemessages.py --add-users
python3 /opt/shuttlemessages/shuttlemessages.py
